[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = [
    '@openzeppelin/contracts@5.3.0/=lib/openzeppelin-contracts/contracts/',
    '@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/',
    '@chainlink/contracts/=lib/chainlink/contracts/',
    '@chainlink/contracts-ccip/contracts/=lib/chainlink-local/lib/chainlink-ccip/chains/evm/contracts/',
    '@chainlink/contracts-ccip/=lib/chainlink-local/lib/chainlink-ccip/',
    '@chainlink/local/=lib/chainlink-local/',
]
evm_version = "cancun"
[profile.ci]
# inherits from default; add CI-specific tweaks here if needed

[rpc_endpoints]
sepolia     = "https://eth-sepolia.g.alchemy.com/v2/J2-qiv8zqLddvSt1qnfrn"
arb-sepolia = "https://arb-sepolia.g.alchemy.com/v2/J2-qiv8zqLddvSt1qnfrn"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
